language: go

go:
- 1.11.x
- 1.12.x
- master

sudo: true

dist: bionic

env:
  - GO111MODULE=on

before_script:
  - sed -i s/bionic/eoan/g /etc/apt/sources.list && apt update && apt --yes full-upgrade
  - apt install libzfslinux-dev

script:
  - echo '############ Code quality ############'
  - go vet ./...
  - FMT=`go fmt ./...` && echo "$FMT" && [ -z "$FMT" ]
  - echo '############ BUILD ############'
  - go build ./...
  - echo '############ Tests ############'
  - go test -coverprofile=coverage.txt -covermode=atomic ./...
  - go test -race ./...
  - echo '############ Assets generated ############'
  - git update-index --assume-unchanged go.* && go generate ./... && MODIFIED=`git status --porcelain --untracked-files=no` && git update-index --no-assume-unchanged go.* && [ -z "$MODIFIED" ] && exit 0 || echo "go generate created modified files" && git --no-pager diff && exit 1
  - echo '############ Modules updated ############'
  - MODIFIED=`git status --porcelain go.sum go.mod` && [ -z "$MODIFIED" ] && exit 0 || echo "go module files aren't up to date" && git --no-pager diff go.mod go.sum && exit 1

after_success:
  - bash <(curl -s https://codecov.io/bash)
